const ActionTypes = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  GET__PRODUCTS_BY_CATEGORY_REQUEST: "GET__PRODUCTS_BY_CATEGORY_REQUEST",
  GET__PRODUCTS_BY_CATEGORY_SUCCESS: "GET__PRODUCTS_BY_CATEGORY_SUCCESS",
  GET__PRODUCTS_BY_CATEGORY_FAILURE: "GET__PRODUCTS_BY_CATEGORY_FAILURE",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAILURE: "GET_CART_FAILURE",

  UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY ",

  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
};

export default ActionTypes;
