const ActionTypes = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

  GET__PRODUCTS_BY_CATEGORY_REQUEST: "GET__PRODUCTS_BY_CATEGORY_REQUEST",
  GET__PRODUCTS_BY_CATEGORY_SUCCESS: "GET__PRODUCTS_BY_CATEGORY_SUCCESS",
  GET__PRODUCTS_BY_CATEGORY_FAILURE: "GET__PRODUCTS_BY_CATEGORY_FAILURE",
};

export default ActionTypes;
